name: Build and push

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * 0'

env:
  TEST_TAG: $GH_USER/$PROGRAM_NAME:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the PREVIOUS_STABLE_ALPINE env
        id: step_one
        run: |
          echo "PREVIOUS_STABLE_ALPINE=`curl -q https://dl-cdn.alpinelinux.org/alpine/ |grep ">v" | cut -d 'v' -f 2 | cut -d '/' -f 1  | sort --field-separator=. --version-sort | tail -2 | head -1`" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set the PREVIOUS_STABLE_ALPINE env
        run: |
          echo "Using alpine version: $PREVIOUS_STABLE_ALPINE"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            ALPINE_VERSION=${{ env.PREVIOUS_STABLE_ALPINE }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64, linux/arm/v7
          tags: |
            ghcr.io/$GH_USER/$PROGRAM_NAME:alpine-${{ env.PREVIOUS_STABLE_ALPINE }}
            ghcr.io/$GH_USER/$PROGRAM_NAME:latest
